# Generated by Django 2.1.2 on 2018-10-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mHotel',
            fields=[
                ('hotel_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('chain_id', models.CharField(max_length=3, null=True)),
                ('hotel_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mHotel',
            },
        ),
    ]
