# Generated by Django 2.1.2 on 2018-10-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=10)),
                ('plan_name', models.CharField(max_length=10)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbook.Hotel')),
            ],
        ),
    ]
