# Generated by Django 2.1.2 on 2018-10-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('room_name', models.CharField(max_length=10)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbook.Hotel')),
                ('plan_id', models.ManyToManyField(to='newbook.Plan')),
            ],
        ),
    ]
