# Generated by Django 2.1.2 on 2018-10-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(max_length=4)),
                ('reserved_out', models.IntegerField(max_length=4)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbook.Hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbook.Room')),
            ],
        ),
    ]
