# Generated by Django 2.1.2 on 2018-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0003_roomstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstock',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='roomstock',
            name='reserved_out',
        ),
        migrations.AddField(
            model_name='roomstock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
