# Generated by Django 2.1.2 on 2018-10-22 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0004_auto_20181022_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstock',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='roomstock',
            name='reserved_out',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
