# Generated by Django 2.1.2 on 2018-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0005_auto_20181022_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
